apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-rffo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-rffo
    app.kubernetes.io/part-of: test-app-pqzp
  name: test-component-rffo
  namespace: build-e2e-owgw-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-rffo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-rffo
    spec:
      containers:
      - image: quay.io/susdas/test-images:68b7deeac763485f8427e5c0667d4399
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
